from flask import Blueprint, request, jsonify
import spotipy
from app.middleware.jwt_auth import require_jwt
from app.services.reccobeats_service import get_audio_features
from app.services.mood_engine import rank_tracks_by_mood

playlist_routes = Blueprint("playlist_routes", __name__, url_prefix="/api/playlist")


@playlist_routes.route("/create", methods=["POST"])
def create_playlist():
    try:
        payload = require_jwt()

        data = request.get_json() or {}
        mood = data.get("mood")
        limit = int(data.get("limit", 30))
        selected_artists = data.get("selected_artists")

        if not mood:
            return {"error": "Mood is required"}, 400

        if not isinstance(selected_artists, list) or len(selected_artists) != 5:
            return {"error": "Exactly 5 selected artists are required"}, 400

        sp = spotipy.Spotify(auth=payload["access_token"])


        track_map = {}
        for artist_id in selected_artists:
            results = sp.artist_top_tracks(artist_id)
            for track in results.get("tracks", []):
                if track.get("id"):
                    track_map[track["id"]] = track["id"]

        track_ids = list(track_map.values())[:50]
        if not track_ids:
            return {"error": "No tracks found from selected artists"}, 400


        audio_features = get_audio_features(track_ids)
        if not audio_features:
            return {"error": "No audio features returned"}, 400


        fixed_features = []
        for i, f in enumerate(audio_features):
            if not isinstance(f, dict):
                continue

            tid = f.get("spotify_id") or f.get("id") or track_ids[i]
            f["id"] = tid
            fixed_features.append(f)

        if not fixed_features:
            return {"error": "Audio features invalid"}, 400


        ranked_tracks = rank_tracks_by_mood(fixed_features, mood)
        if not ranked_tracks:
            return {"error": "Ranking failed"}, 400

        top_tracks = [t for t in ranked_tracks if t.get("id")][:limit]
        track_ids = [t["id"] for t in top_tracks]
        spotify_tracks = sp.tracks(track_ids)["tracks"]

        track_uris = [f"spotify:track:{t['id']}" for t in top_tracks]

        if not track_uris:
            return {"error": "No valid track URIs"}, 400


        user = sp.current_user()

        playlist = sp.user_playlist_create(
            user=user["id"],
            name=f"Vibexx • {mood.capitalize()}",
            public=False,
            description=f"Mood-based playlist generated by Vibexx",
        )

        for i in range(0, len(track_uris), 100):
            sp.playlist_add_items(playlist["id"], track_uris[i:i+100])
        
        tracks_payload = []
        for t in spotify_tracks:
            tracks_payload.append({
        "id": t["id"],
        "name": t["name"],
        "artists": [a["name"] for a in t["artists"]],
        "album_name": t["album"]["name"],
        "image": t["album"]["images"][0]["url"] if t["album"]["images"] else None,
        "spotify_url": t["external_urls"]["spotify"],
    })
        artists_info = sp.artists(selected_artists)["artists"]
        selected_artists_payload = [
    {
        "id": a["id"],
        "name": a["name"],
        "image": a["images"][0]["url"] if a["images"] else None,
    }
    for a in artists_info
]
        

        return {
            "playlist_name":playlist['name'],
            "mood":mood,
            "selected_artists": selected_artists_payload,
            "playlist_id": playlist["id"],
            "playlist_url": playlist["external_urls"]["spotify"],
            "track_count": len(track_uris),
            "tracks": tracks_payload,
        }

    except Exception as e:
        return jsonify({"error": str(e)}), 401